php-api:
    build: ./docker/api
    links:
        - db
    volumes:
        - ./api:/var/www/app
nginx-api:
    image: nginx:stable
    links:
        - php-api
    volumes_from:
        - php-api
    volumes:
        - ./docker/api/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "8080:80"
db:
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: app
        MYSQL_USER: app
        MYSQL_PASSWORD: app
php-app:
    build: ./docker/app
    links:
        - nginx-api
    volumes:
        - ./app:/var/www/app
nginx-app:
    image: nginx:stable
    links:
        - php-app
    volumes_from:
        - php-app
    volumes:
        - ./docker/app/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "80:80"
behat:
    build: ./docker/behat
    links:
        - nginx-api
        - nginx-app
        - db
    volumes:
        - .:/opt/behat
